### ISSUE TITLE
[BUG] 상품이 계속 준비중으로 나옵니다.

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-11#217]
상품을 클릭하면 아래의 화면에서 더 진행이 되지 않습니다.

<img width="1440" alt="스크린샷 2019-12-06 오후 3 09 02" src="https://user-images.githubusercontent.com/20928548/70300292-7b0f6e00-183a-11ea-834d-271a1807c368.png">

**Comment by sphong5911** [comment]
현재 시드 데이터가 등록이 안된 상태라 상품을 불러올 수가 없습니다 😢 
금방 조치하도록 하겠습니다.

**Comment by sphong5911** [comment]
현재 서버 배포가 정상적으로 이루어져 상품 조회가 정상적으로 작동합니다. 버그 리포트 감사합니다!
