### ISSUE TITLE
[BUG] 로그인을 했을 때, 아무런 액션이 나오지 않습니다.

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-11#218]
로그인을 했지만, 로그인 액션이 아무것도 이루어지지 않습니다.

**Comment by sphong5911** [comment]
CORS 이슈로 현재 로그인이 되지 않는 상태입니다 😢 
빠르게 조치하도록 하겠습니다.

**Comment by sphong5911** [comment]
현재 배포가 이루어져 로그인이 정상적으로 동작합니다. 버그리포트 감사합니다!
