### ISSUE TITLE
[BUG] 고양이를 눌렀는데 등록된 상품이 없다고 나옵니다

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-11#220]
! 고양이를 눌렀는데 등록된 상품이 없다고 나옵니다

**Comment by sphong5911** [comment]
배포 서버에 문제가 생겨 데이터가 들어가지 않았었습니다ㅠㅠ 감사합니다!!

**Comment by sphong5911** [comment]
현재 배포가 정상적으로 이루어져 조회가 가능합니다. 버그리포트 감사합니다!
