### ISSUE TITLE
[BUG] 채팅이 여러개로 보내지는 현상이 있습니다.

### ISSUE THREAD

**Issue by GirlFriend-Yerin** [connect-foundation/2019-11#255]
Browser : Chrome
OS : Windows 10
Page : products/

상황
1. 상품 페이지로 들어간다.
2. 로그인 / 로그아웃을 반복한다.
3. 횟수만큼 메세지가 보내진다.

해결해주세요!

**Comment by sphong5911** [comment]
해당 현상은 해결되어 close 하겠습니다.
