### ISSUE TITLE
[Bug] 비로그인 시에도 판매자와 대화하기가 활성화되는 현상

### ISSUE THREAD

**Issue by sphong5911** [connect-foundation/2019-11#270]
비로그인한 사용자는 나타나지 않지만 판매자의 메신저에는 사용자 정보가 비어있는 채팅방이 생성되는 현상이 있음.
![image](https://user-images.githubusercontent.com/37038262/70766264-929da800-1da0-11ea-9199-6d25bd39c7f4.png)
![image](https://user-images.githubusercontent.com/37038262/70766271-9a5d4c80-1da0-11ea-8187-53059ca1505c.png)

**Comment by deokisys** [comment]
해결했습니다!
