### ISSUE TITLE
[BUG] CSS 오류

### ISSUE THREAD

**Issue by teihong93** [connect-foundation/2019-11#275]
<img width="444" alt="스크린샷 2019-12-13 오후 2 44 21" src="https://user-images.githubusercontent.com/52785648/70772233-40b44c80-1db7-11ea-8bc5-ab0dd71e9784.png">
- 경매 의 경이 짤림

**Comment by sphong5911** [comment]
해당 이슈는 현재 확인이 되지않고 있는 상황입니다. 확인되는 즉시 수정하도록 하겠습니다.

**Comment by deokisys** [comment]
- 모니터가 작아서 그런것으로 예상이됩니다 . 큰화면에서 이용해주시길 바랍니다. 죄송합니다.
