### ISSUE TITLE
구글로 가입할 시 회원 이름이 나오지 않고, 이상한 숫자? 가 나오는 현상

### ISSUE THREAD

**Issue by riverandeye** [connect-foundation/2019-11#278]
![image](https://user-images.githubusercontent.com/41494099/70772346-8ec95000-1db7-11ea-8a9a-567855c9f872.png)

채팅창에 작성하였을 때, 좌측에는 사용자 이름이 잘 뜨지만, 대화창에서는 알 수 없는 숫자가 뜹니다.

**Comment by GirlFriend-Yerin** [comment]
해당 부분은 현재 수정 중에 있습니다.
이후 아이디 또는 이름으로 표시될 예정입니다.

**Comment by sphong5911** [comment]
해당 이슈는 해결되어 close
