### ISSUE TITLE
[BUG]0원에 입찰됩니다

### ISSUE THREAD

**Issue by lallaheeee** [connect-foundation/2019-11#282]
![image](https://user-images.githubusercontent.com/22452742/70772803-06e44580-1db9-11ea-9325-dccd9c1561b7.png)

6,000,000원을 입력했더니
0원에 입찰로 되었습니다.

**Comment by load0ne** [comment]
저도 같은 현상이 있습니다

<img width="433" alt="스크린샷 2019-12-13 오후 3 00 12" src="https://user-images.githubusercontent.com/47515936/70773051-adc8e180-1db9-11ea-9ada-e8ef58851139.png">

**Comment by sphong5911** [comment]
해당 버그는 한글을 입력후 입찰했을때 발생했던 버그인가요?

**Comment by young-do** [comment]
그리고 0원에 입찰되면 1원 입찰해도, 0원으로 입찰되었다고 뜨네요!
