### ISSUE TITLE
[BUG] CSS

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-11#284]
![Screen Recording 2019-12-13 at 3 16 41 PM](https://user-images.githubusercontent.com/28642472/70773918-1d3fd080-1dbc-11ea-8990-3a33a3221bd0.gif)

**Comment by sphong5911** [comment]
?????

**Comment by inthewalter** [comment]
![Screen Recording 2019-12-13 at 3 16 41 PM](https://user-images.githubusercontent.com/28642472/70774217-ecac6680-1dbc-11ea-8ef0-89aace0ffd5c.gif)
호버시 1두둠칫입니다.

**Comment by sphong5911** [comment]
해당 이슈는 화면의 크기가 충분하지 않아 발생하는 것으로 보입니다. 큰 화면에 맞춰 제작되었기 때문에 다르게 보일 수 있습니다.
