### ISSUE TITLE
[bug] 최소 금액 표시 에러 납니다

### ISSUE THREAD

**Issue by ktseo41** [connect-foundation/2019-11#285]
<img width="477" alt="스크린샷 2019-12-13 오후 3 23 41" src="https://user-images.githubusercontent.com/6429885/70774121-a951f800-1dbc-11ea-9f69-3f21b4983a8c.png">

0원으로 입찰한 후에 에러가 났어요

**Comment by sphong5911** [comment]
해당 버그는 확인중에 있습니다. 버그 리포트 감사합니다!
