### ISSUE TITLE
[BUG] 편차 -값 나와요.

### ISSUE THREAD

**Issue by bellaah** [connect-foundation/2019-11#286]
![](https://i.imgur.com/FtmNzvN.png)
편차가 마이너스 값이 나와요!

**Comment by sphong5911** [comment]
편차 - 는 의도된 값입니다!
-가 나왔다면 판매자가 희망한 가격보다 낮게 팔린 경우이고
+의 경우 판매자가 희망한 가격보다 높게 팔린 경우입니다!
