### ISSUE TITLE
[Bug] 브라우저 width값이 충분히 크지 않으면 채팅이 본문을 가립니다

### ISSUE THREAD

**Issue by dhmin5693** [connect-foundation/2019-11#321]
![image](https://user-images.githubusercontent.com/15965611/71070448-236bed80-21be-11ea-9ec2-26acf29a694a.png)

Chrome, Firefox 최신 버전에서 확인
브라우저 상관 없이 발생하는 것으로 추정됩니다.

**Comment by deokisys** [comment]
- 작은화면보다 큰화면에 맞춰 제작하여 큰화면에서 이용해주시길 바랍니다. 죄송합니다.
