### ISSUE TITLE
[Bug] 카카오톡 공유 기능이 작동하지 않습니다.

### ISSUE THREAD

**Issue by dhmin5693** [connect-foundation/2019-11#322]
![image](https://user-images.githubusercontent.com/15965611/71070531-57471300-21be-11ea-8eaf-863cc94a49ba.png)

재현 방법
1. http://devtest.palda.shop/products/1058 접속
2. Kakao Talk 버튼 클릭

**Comment by GirlFriend-Yerin** [comment]
해결되었습니다.
