### ISSUE TITLE
[건의] URL 공유 버튼 작동 여부를 사용자가 알 수 있게 해주세요.

### ISSUE THREAD

**Issue by dhmin5693** [connect-foundation/2019-11#323]
**재현 방법**
1. http://devtest.palda.shop/products/1058 접속
2. URL 버튼 클릭

**결과**
1. 클립보드에 현재 페이지의 URL (http://devtest.palda.shop/products/1058)이 복사된다.

**건의**
1. 'URL이 복사되었습니다.' 와 같이 Alert 창을 띄워 사용자가 인지할 수 있도록 하면 좋을 것 같습니다.

**Comment by sphong5911** [comment]
상황과 건의사항을 자세하게 설명해주셔서 감사합니다. 해당사항은 논의하여 반영여부를 결정하도록 하겠습니다.

**Comment by sphong5911** [comment]
URL복사 시 alert를 띄워주는 기능 반영하였습니다.
