### ISSUE TITLE
[6-1-2] Create keyword notification server using mail API

### ISSUE THREAD

**Issue by GirlFriend-Yerin** [connect-foundation/2019-11#89]
메일을 이용한 알림 서비스를 제작합니다.

사용자가 등록한 키워드에 맞춰 물품이 등록될 시 메일이 발송됩니다.

**Comment by deokisys** [comment]
->
메일알림에는 자신이 판매한 상품이 구매가 되었거나, 상품을 구매했을때 메일 알림이 전송됨.
